### PR TITLE
Selected product show

### PR DESCRIPTION
**Pull request by lurelureg**
Instead of adding a product card I decided to add the name of the product directly in the title of the stack so not to create a loop of user interaction. 

image

### CODE REVIEW

**Review by martajasinska — COMMENTED** [review]
What has changed? I see changes from Prettier and I the ones I made in the API-call branch (I guess bc of rebase?) and it's hard to find the actual update

**Comment by lurelureg** [comment]
> What has changed? I see changes from Prettier and I the ones I made in the API-call branch (I guess bc of rebase?) and it's hard to find the actual update

I could not avoid it this time, but 1 commit is only 1 line and the other is only 3 files, you can skip checking the APP file which is the most complex.

**Comment by lurelureg** [comment]
> What has changed? I see changes from Prettier and I the ones I made in the API-call branch (I guess bc of rebase?) and it's hard to find the actual update

I could not avoid it this time, but 1 commit is only 1 line and the other is only 3 files, you can skip checking the APP file which is the most complex.

**Comment by lurelureg** [comment]
change in APP.js 
line 66

**Review by martajasinska — APPROVED** [review]

**Pull request merged**
